/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./pages/**/*.html",
    "./js/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#ecf2ee",
        "on-background": "#171d1b",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "primary": "#006b58",
        "secondary-fixed": "#a7f1df",
        "on-primary-fixed": "#002019",
        "tertiary-fixed": "#dbe4e2",
        "primary-container": "#0daa8d",
        "on-secondary-fixed": "#00201b",
        "on-tertiary-fixed": "#151d1c",
        "surface-container": "#e9efeb",
        "on-tertiary-container": "#283130",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#005142",
        "on-secondary": "#ffffff",
        "tertiary-container": "#909997",
        "secondary-container": "#a7f1df",
        "secondary": "#1a6a5c",
        "primary-fixed": "#79f8d7",
        "primary-fixed-dim": "#5adbbc",
        "secondary-fixed-dim": "#8bd4c4",
        "on-secondary-container": "#237062",
        "on-primary-container": "#00362b",
        "inverse-surface": "#2b322f",
        "surface-container-highest": "#dee4e0",
        "surface": "#f5fbf7",
        "on-secondary-fixed-variant": "#005045",
        "surface-container-lowest": "#ffffff",
        "outline": "#6c7a75",
        "outline-variant": "#bbcac3",
        "surface-variant": "#dee4e0",
        "tertiary": "#57605f",
        "inverse-primary": "#5adbbc",
        "on-tertiary-fixed-variant": "#404847",
        "surface-container-high": "#e3eae6",
        "surface-bright": "#f5fbf7",
        "tertiary-fixed-dim": "#bfc8c7",
        "surface-dim": "#d5dbd7",
        "background": "#f5fbf7",
        "surface-container-low": "#eff5f1",
        "on-error-container": "#93000a",
        "on-surface": "#171d1b",
        "error-container": "#ffdad6",
        "surface-tint": "#006b58",
        "on-primary": "#ffffff",
        "on-surface-variant": "#3d4945",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "20px",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        xs: "4px",
        lg: "40px",
        gutter: "24px",
        xl: "64px",
        sm: "12px",
        md: "24px",
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
